---
# tasks file for ansible-role-vault-init

- name: Initialise vault
  uri:
    url: "http://{{ vault_addr }}:{{ vault_port }}/v1/sys/init"
    validate_certs: no
    method: PUT
    body: "{{ lookup('file','init_params.json') }}"
    body_format: json
    return_content: yes
    status_code: 200
  become: no
  register: vault_init
  run_once: yes

- name: Save keys locally
  copy:
    content: "{{ vault_init.json }}"
    dest: "{{ vault_keysfile }}"
    mode: 0600
  delegate_to: localhost
  become: no
  no_log: no
  when: vault_init is not skipped
  run_once: yes

- name : source bash profiles
  shell: source ~/.bashrc
  args:
    executable: /bin/bash
